### ISSUE TITLE
Force "fixed ladder"

### ISSUE THREAD

**Issue by Jowat97** [lkmvip/netflix-4K-DDplus#10]
Hello there,

first at all thank you very much for this great extension!

As you may noticed, Netflix has changed the bitrate ladder system through the so called "4K VMAF model".  4K Content, which used to be played with 16.000 kbps will now be played with ~9000 kbps or even lower, because of a "better compression".
More info: https://netflixtechblog.com/optimized-shot-based-encodes-for-4k-now-streaming-47b516b10bbb

However, the quality is really worse compared to the regular "ladder model". Is it somehow possible, to force Netflix to use the old ladder system, instead of the new "VAMP model"?

BR

**Comment by lkmvip** [comment]
no, because the new 4K video can only be played with "VAMP"

"VAMP" uses "hevc-main10-L(*)-dash-cenc-prk-do"

https://www.netflix.com/title/81011660
need it ,lf lost  ,then only 1080P

**Comment by Jowat97** [comment]
Okay, I see. Thank you.

Besides that, have you considered to put your Extension into the Extensions Store from Microsoft Edge?
https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home

I think a lot of people would like to use this extension, but don't know how to do it manually.

**Comment by lkmvip** [comment]
ok ,i try

**Comment by lkmvip** [comment]
ok ,i try

**Comment by 5J2J** [comment]
How do I see in 4K having Microsoft Edge 85.0.564.70?
I have Windows 10 pro.

**Comment by Jowat97** [comment]
@5J2J This is not the right issue for your topic. And lkmvip has already put a link in his description for this.
To watch Netflix in 4K, read this article: https://help.netflix.com/en/node/13444
This AddOn can't force 4K, if your Computer/Monitor is not capable of it.

**Comment by 5J2J** [comment]
> @ 5J2J Este no es el problema adecuado para su tema. Y lkmvip ya ha puesto un enlace en su descripción para esto.
> Para ver Netflix en 4K, lea este artículo: https://help.netflix.com/en/node/13444
> Este complemento no puede forzar 4K, si su computadora / monitor no es capaz de hacerlo.

I meet all the requirements but it won't let me put it in 4K, however, I use the official Netflix application from the microsoft store if it works for me in 4K.
I would like to be able to watch in 4K with the browser.

**Comment by lkmvip** [comment]
If your Netflix APP can watch 4K, then try the following
1,dont use portable version EDGE
2,win10 ver >= 1908
3,try win10 system recovery

or try install this，You must first uninstall all the 'HEVC Video Extensions' and restart the PC
https://www.microsoft.com/en-sg/p/hevc-video-extensions-from-device-manufacturer/9n4wgh0z6vhq?activetab=pivot:overviewtab

**Comment by 5J2J** [comment]
I have version 1903 of Windows 10 pro.
Do I have to upgrade to 1908?
With the 'HEVC video extensions' I can watch in 4K from the Microsoft Netflix app, but not from Microsoft Edge, only 1080 is enabled on Microsoft edge.

I have Microsoft Edge
Version 85.0.564.70 (Official Build) (64-bit)

**Comment by lkmvip** [comment]
There are different versions of'HEVC Video Extensions' (free and paid), use the version I posted above

If it still doesn't work, try in order, 'system restore', 'upgrade system'


I had this problem in 1809 before, and it was resolved after upgrading to 2004

**Comment by 5J2J** [comment]
I just realized that it no longer works in microsfot application.
Netflix disabled 4k due to coronavirus or is it just me?

**Comment by 5J2J** [comment]
![image](https://user-images.githubusercontent.com/62446608/95547342-2946ef80-09d9-11eb-8394-d06dac6c1f2a.png)

I reinstalled HEVC and it worked again in the microsoft application, but it still does not work in the browser, I am going to try to update windows 10.

![image](https://user-images.githubusercontent.com/62446608/95547635-c99d1400-09d9-11eb-93db-8ef5c2b0de21.png)

**Comment by lkmvip** [comment]
now submitted to the store

https://microsoftedge.microsoft.com/addons/detail/oikpkeeoofpiapmjioabikmgjeaoggcn
