### ISSUE TITLE
安了插件码率只能到720p

### ISSUE THREAD

**Issue by SCOTTCUI1224** [lkmvip/netflix-4K-DDplus#12]
求解。。

**Comment by SCOTTCUI1224** [comment]
![QQ截图20201122094839](https://user-images.githubusercontent.com/62314613/99891714-ea7aa980-2ca7-11eb-856f-b04f79b9755b.png)
win10 20h2版本 edge最新版

**Comment by lkmvip** [comment]
dont use portable version edge
its only 720P

**Comment by SCOTTCUI1224** [comment]
我是傻子，谢谢了 ！
