### ISSUE TITLE
Nothing happens when I click on the Icon

### ISSUE THREAD

**Issue by vaishnavm217** [lkmvip/netflix-4K-DDplus#13]
![image](https://user-images.githubusercontent.com/17612112/100701434-b6993580-33c5-11eb-90fb-ea05f88887c4.png)
This error is there when i try to click on the extension

**Comment by lkmvip** [comment]
right click icon

**Comment by Dark4Codrutz** [comment]
This extension has no floatable UI .
Just right click it and go to Extension Settings, there you'll get the UI and the toggles.

**Comment by AymanTanvir101** [comment]
Works really fine for me! Is there any extension to play DDPlus audio in chrome?
