### ISSUE TITLE
CAN NOT PLAY WHEN CHECKED Use ddplus and Atmos(if any) track got D7361-1254

### ISSUE THREAD

**Issue by blankhang** [lkmvip/netflix-4K-DDplus#14]
IF CHECKED Use ddplus and Atmos(if any) track got D7361-1254
AND CHECKED Use AVC, NOT Avchigh video OR Disguised as Edge (if you can`t watch 4K)  code got D7111-1331

**Comment by blankhang** [comment]
![image](https://user-images.githubusercontent.com/3981276/100751386-3654ed80-3422-11eb-921b-c6b3f6a3f9c6.png)
![image](https://user-images.githubusercontent.com/3981276/100751431-48cf2700-3422-11eb-83f6-8afd2845d5d5.png)

![image](https://user-images.githubusercontent.com/3981276/100751499-57b5d980-3422-11eb-9be9-060c65a202f3.png)
![image](https://user-images.githubusercontent.com/3981276/100751535-68664f80-3422-11eb-81ce-11a54bd7b782.png)

**Comment by lkmvip** [comment]
win7？

**Comment by lkmvip** [comment]
see README.md

Recommended software:
1,Win10.Ver.2004
2,MsEdge>V81(In non-win10 or portable version, WidevineCdm will be used, its = Chrome)

win7 is use WidevineCdm ,ddpls and avc feature is not work

It's time to give up win7, friend

**Comment by blankhang** [comment]
i am using WIN10 20H2 and MsEDGE V87

**Comment by lkmvip** [comment]
you edge is portable version?

if not, you need to reinstall win10
if yes, dont use portable version

because your 'PlayReadyCdm' is not working

**Comment by blankhang** [comment]
not my edge is not portable version
but my win10 is lite version
maybe it's the problem
tonight i will try to reinstall win10 and then try again

**Comment by blankhang** [comment]
thanks after i reinstall win10 now DDPLUS5.1 is working again :D

**Comment by Dark4Codrutz** [comment]
> thanks after i reinstall win10 now DDPLUS5.1 is working again :D

Close Issue ?
