### ISSUE TITLE
Any way to play DDPlus 5.1 in prime video?

### ISSUE THREAD

**Issue by AymanTanvir101** [lkmvip/netflix-4K-DDplus#17]
Thanks for making such a cool extension! It works really great for me! ♥ I'm wondering is there any way to play DDPlus 5.1 in amazon prime video? 

Also can we get an extension for chrome where AVCHigh can be disabled? 
Cause sometimes there are better bitrate in AVC main.. Though this extension works nicely with edge in AVC main, but can we get a version for chrome too? :)

**Comment by lkmvip** [comment]
1,can‘t
2,can‘t

**Comment by karvai** [comment]
> 2,can‘t

Do you know if that is possible? I mean main on chrome.

**Comment by lkmvip** [comment]
no
