### ISSUE TITLE
Not getting the highest available audio bitrate!

### ISSUE THREAD

**Issue by Randomcoolguy123** [lkmvip/netflix-4K-DDplus#18]
Though this extension worked fine previously, but it's not playing DDP5.1 Atmos at 768kbps or DDP5.1 at 640kbps from today! Rather I'm getting a maximum of 448kbps for DDP5.1 Atmos and 256kbps for DDP5.1! Don't know why. It's also showing some error/invalid message in the network tab!

Screenshots for DDP5.1 Atmos: https://s2.gifyu.com/images/imagee77bfd03a599c643.png
Also can't switch from one audio to another.. It goes into loading for eternity.
Invalid Message: https://s2.gifyu.com/images/image351d21fc30fe58ca.png
For instance you may check Snowpiercer S01E01 or S02E01.
Don't know if there are issues with other titles also.
Hoping for a fix soon
Thanks!

**Comment by lkmvip** [comment]
https://microsoftedge.microsoft.com/addons/detail/oikpkeeoofpiapmjioabikmgjeaoggcn
