### ISSUE TITLE
Ignore Skip button shortcut

### ISSUE THREAD

**Issue by Jowat97** [lkmvip/netflix-4K-DDplus#19]
Hello @lkmvip,

Netflix introduced a couple month ago the "skip-button". With the skip-button, it is possible to skip the intro. They also have a shortcut for this button, which is the letter 'S'.
However, if I want to open the bitrate-menu by pressing CTRL-ALT-SHIFT-S, Netflix recognizes the 'S' key and skips the intro, instead of opening the bitrate-menu.

So, is it somehow possible to add a function in the AddOn, to disable the shortcut 'S' for the skip-button? Thank you for your support and time!

Best Regards!

**Comment by lkmvip** [comment]
i cant
