### ISSUE TITLE
Actually 4k works also on Edgium 83+

### ISSUE THREAD

**Issue by Manu99it** [lkmvip/netflix-4K-DDplus#2]
I've drm flags enabled. 4k still works, and finally also 5.1 audio, thank you! Finally i can get rid of the shit of app

![image](https://user-images.githubusercontent.com/19348772/83932990-33e04680-a7a5-11ea-96aa-b7bd446316af.png)

**Comment by lkmvip** [comment]
ok，thanks for your report
maybe it’s the portable version so I can’t watch it

**Comment by jackdiy** [comment]
Can I ask two questions:
1. Can I watch 4K on a display device that only supports 1080P
2. Is there a way to download 4K video locally after successfully watching 4K?

**Comment by Manu99it** [comment]
no and no
