### ISSUE TITLE
Use AVC, NOT AvcHigh video code - not working

### ISSUE THREAD

**Issue by karvai** [lkmvip/netflix-4K-DDplus#21]
It looks like it stopped working.

Error D7111-1331

**Comment by karvai** [comment]
Working now

**Comment by erickyun** [comment]
> Working now

I do have the same problem. For me it isn't working?
How did work for you?

**Comment by erickyun** [comment]
> Working now

@karvai 
I do have the same problem. For me it isn't working?
Could you tell me How it did work for you?

**Comment by xKyoGox** [comment]
@erickyun 

same thing was happend to me like showing **Error D7111-1331**

Just enable **PlayReady DRM for Windows 10** through **edge://flags/**

Mine is working fine without any errors now
