### ISSUE TITLE
Any way to list and choose all supported codecs of a movie?

### ISSUE THREAD

**Issue by Felixkruemel** [lkmvip/netflix-4K-DDplus#22]
I know that Netflix delivers shows in different codecs,
some in old AVC, some in newish HEVC (if supported by Hardware) but on Android even in AV1 on SD quality.

So could there be a way to force an codec (like e.g. force HEVC, even if I have no HW accelerated playback)?

**Comment by lkmvip** [comment]
HEVC code only work on HDCP2.2 and Original dramas and movies

**Comment by Felixkruemel** [comment]
> HEVC code only work on HDCP2.2 
That's not true.

My Display is not HDCP2.2 (that's the reason why I'm watching in 1080p) but still uses HEVC
![grafik](https://user-images.githubusercontent.com/12109804/108867748-cbb4e780-75f5-11eb-8b01-57c93cadd372.png)
