### ISSUE TITLE
Netflix just throws an error since today

### ISSUE THREAD

**Issue by Felixkruemel** [lkmvip/netflix-4K-DDplus#23]
If I click on a show it will just display "Something went wrong" or something like that. When I disable the addon everything works fine.

I also unticked every box in the addons setting but still the same thing.

Console log:
![image](https://user-images.githubusercontent.com/12109804/110984934-12cc0800-836c-11eb-9d28-03a0e836b84b.png)

**Comment by Felixkruemel** [comment]
Okay, interesting. Version 1.3 still works.

I cloned the git repo and installed it via the folder, there it works and shows me V1.3 in the settings

**Comment by fahmimuh** [comment]
i got the error too, how do you install it via folder? can you explain it?

**Comment by Felixkruemel** [comment]
> i got the error too, how do you install it via folder? can you explain it?

You download the code from Github and extract everything into a folder. Then you go to the extension settings page in Edge and enable developer mode on the bottom left. Then you can select a folder to load an extension and just do that.

**Comment by lkmvip** [comment]
OK,I have fixed
![1](https://user-images.githubusercontent.com/12974141/111009354-52c3d700-83ce-11eb-9a3e-59615440fffb.png)

**Comment by Felixkruemel** [comment]
@lkmvip Could you tag each release in GitHub too? :)

**Comment by lkmvip** [comment]
> @lkmvip Could you tag each release in GitHub too? :)

ok
