### ISSUE TITLE
Doesn't seem to work when using 4K Smart TV as monitor

### ISSUE THREAD

**Issue by cavalia88** [lkmvip/netflix-4K-DDplus#24]
No access to a 4K computer monitor unfortunately, so I was testing this on a 4K LG Smart TV. Didn't have any luck with the 4K LG Smart TV, only managed to get 1080p, no 4K output.

Connected my PC to the 4K LG Smart TV and Nvidia Control Panel indicates both graphics card and LG TV are HDCP enabled.

**Comment by Xtravaganz** [comment]
You connected only the 4K LG monitor?

**Comment by cavalia88** [comment]
Yes, I disabled my computer monitor. Only LG TV connected to the PC.

**Comment by Phoenomenal** [comment]
You need HDCP 2.2  to watch Netflix in 4K.  Try to test your system with  free program CyberLink Ultra HD Blu-ray Advisor  and see do you pass HDCP 2.2 (GPU/Display) requirement  and don't bother   with Intel SGX , protected audio  etc its not needed for 4K in Netflix.

And install  HEVC extension from microsoft store  if you dont have it  -    https://www.microsoft.com/en-us/p/hevc-video-extensions-from-device-manufacturer/9n4wgh0z6vhq?activetab=pivot:overviewtab

**Comment by lkmvip** [comment]
see  https://help.netflix.com/zh-tw/node/13444


Your TV must support 4K@60Hz

**Comment by cavalia88** [comment]
I tested with CyberLink Ultra HD Blu-ray Advisor , passed the HDCP 2.2 (GPU/Display) test. Also passed the HEVC -10bit test

Yes, the LG 4K TV supports 4K@60Hz as far as I can tell. TV model is LG-49UJ632T with specifications at https://www.lg.com/my/tvs/lg-49UJ632T

**Comment by Phoenomenal** [comment]
HEVC video extension from microsoft  store is installed ?   Stupid question but still -  you have Netflix  Premium plan (ULTRA HD) ?

If so everything should be ok,  i have 4k (with this extension) even on 1440p monitor (with 1440  max without netflix 4k ddplus extension)  in Netflix using  Microsoft Edge 

You might try to see if  Netflix win 10 app playing  4k  .

And also  do  this in microsoft edge browser:

Head to edge://settings/help to ensure you're on the latest version of microsoft edge, then over to edge://flags/#edge-playready-drm-win10 and enable that flag (both updating and enabling this flag will restart the browser).  After the restarts, ensure you have hardware acceleration toggled on here: edge://settings/system.

**Comment by cavalia88** [comment]
Yes, I'm on the Netflix Premium plan (Ultra HD). 

Is the HEVC extension required? Windows Store wants to charge me for the HEVC extension. I currently already have other HEVC decoders installed for my other media players.

I installed the Windows 10 App Store Netflix app. Same issue, can only play at 1080p.

I installed the native LG WebOS Netflix app and it works flawlessly, playing out at 4k resolution.

**Comment by Phoenomenal** [comment]
HEVC extension  is indeed required.  

 Its 1$    but have also free version :   https://www.microsoft.com/en-us/p/hevc-video-extensions-from-device-manufacturer/9n4wgh0z6vhq?activetab=pivot:overviewtab

After you install either this free version from Device Manufacturer  or paid version (they same, microsoft just greedy)  reboot your pc and 4K in Netflix should work.

**Comment by cavalia88** [comment]
I installed the free HEVC extension. Netflix Windows 10 app is now able to get 4K playback.

No luck with the Chrome browser, it still plays 1080p only. I followed your various instructions but still doesn't work. No settings required on the "netflix-4K-DDplus" extension correct?

**Comment by Phoenomenal** [comment]
Chrome wont play 4K in Netflix no matter what because Chrome use Widevine DRM.    You need Microsoft Edge browser  which use Playready DRM  needed to 4K on Netflix   (new version of Edge based on Chromium Engine  which supports all extensions from Chrome)   
 
And you actually dont need to enable settings on "netflix-4K-DDplus" extension  to get 4k but i reccomend to enable : Automatically select best bitrate available  and  Use ddplus and Atmos(if any) track

**Comment by cavalia88** [comment]
I typed wrongly. I meant that even after installed the HEVC extensions, I was only able to obtain 1080p on the Edge browser. Not sure what else I can try

It works fine on the Netflix Win10 App and the native LG WebOS app. Think I was just use either one of these.

**Comment by markey** [comment]
So for me with the latest code from Git Master, Edge Dev-Channel, plus HEVC, on my 34" Ultrawide monitor:  Netflix is giving me the 4k stream. So far so good!

However: At the end of each episode when Netflix tries to play the next episode of a series, it's throwing an error: D7361-1253

If I manually skip to the next episode, all is good. Error only happens on auto-play.

**Comment by cavalia88** [comment]
My guess is that Netflix somehow is able to detect that my display is a "LG Smart TV" based on the display name, and prevents 4K playback through the Edge browser.  The Windows 10 Microsoft Netflix App allows for 4K playback on my LG Smart TV though

Has anyone managed to get this extension working on a 4K Smart TV display (be it LG, Samsung, Sony etc)?

**Comment by Dark4Codrutz** [comment]
I add to this discussion that newer Edge browser versions (starting in Beta channel) now include HDCP 2.2 support status under **Media Foundation Rendering Capabilities** in about://gpu page, among other thins.
This makes it an excellent point to start troubleshooting issues with 4k streaming as you can see if everything is working properly on your backend side, like:
- PlayReady Hardware DRM disabled | false
- Direct Composition | true
- HEVC installed | true
- HEVC activable | true
- HDCP 2.2 support | true
- HEVC - 4K support | true

If those doesn't match then there is nothing any extensions can do for you.
