### ISSUE TITLE
Add LC-AAC audio option

### ISSUE THREAD

**Issue by Sunspark-007** [lkmvip/netflix-4K-DDplus#26]
With version 1.41, if the audio option "Use ddplus and Atmos(if any) track" is checked, then it will use mp4a.a6 which is ddplus codec. If this option is not checked, it will use mp4a.40.5 which is he-aac. However, there is another audio codec which is selectable by the Win10 netflix app, mp4a.40.2 which is lc-aac and this one uses the same bitrate as the ddplus codec and is better sound than he-aac (which uses a lower bitrate). 

Every system is different, but perceptually to an analog stereo output generally he-aac will sound muted compared to ddplus which sounds loud and boomy. lc-aac seems to be in the middle between the two.

Why not use the app then you might say? Unfortunately region hopping can't be done on the app with the same ease as a browser setup. In that circumstance one is then limited to only he-aac or ddplus.

**Comment by lkmvip** [comment]
Unfortunately region hopping can't be done on the app with the same ease as a browser setup. In that circumstance one is then limited to only he-aac or ddplus.

**Comment by Sunspark-007** [comment]
Can the browser use lc-aac audio, or is it just he-aac only? Why can't lc-aac be selected if ddplus can be selected because ddplus does not appear on its own.
