### ISSUE TITLE
Extension doesn't work anymore  with  Test participation  option enabled in account settings

### ISSUE THREAD

**Issue by Phoenomenal** [lkmvip/netflix-4K-DDplus#28]
As a title name say  extension doesn't work at all now no matter what options check/ uncheck :  no ddplus,  no  all tracks and subs and no avc instead of avchigh  .

**Comment by Phoenomenal** [comment]
Just needed to disable "test participation"  in account settings to make everything work again.   lkmvip,  i think its not a bad idea to keep thread open for the time being for people with the same issue  to know how to fix it.

**Comment by lkmvip** [comment]
It may be an individual case
I also turned on "Participate in the test", but everything is ok
