### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by p2mgrup** [lkmvip/netflix-4K-DDplus#29]
Hello,
Is it possible to change something in your extension to make a work in win7 (Chrome)?
Thanks! :)

**Comment by lkmvip** [comment]
https://github.com/jangxx/netflix-1080p

**Comment by p2mgrup** [comment]
Hi,
Thank you, but in that version is not possible(?) to open a video from Main profile, only HIGH.
Do you know how we can add this profile to Player?

**Comment by lkmvip** [comment]
only Windows 10 64-bit, MicrosoftEdge(Chromium core)

**Comment by p2mgrup** [comment]
Ok, thank you!
