### ISSUE TITLE
求个 Chrome 版

### ISSUE THREAD

**Issue by xyr5668** [lkmvip/netflix-4K-DDplus#3]
大佬这个的版本再移植回 Chrome 有难度吗，求一个 Chrome 版 thx

**Comment by lkmvip** [comment]
Chrome插件看这里
https://github.com/truedread/netflix-1080p

我用的playercore是edge的，不能在Chrome上使用，而且Chrome不支持ddplus，也不支持PlayReadyCdm。

**Comment by xyr5668** [comment]
我就是从那个项目找过来的，不是在Chrome 上不能用了么
2020年6月12日 +0800 PM2:33 lkmvip <notifications@github.com>，写道：

**Comment by lkmvip** [comment]
https://github.com/truedread/netflix-1080p/pull/95#issuecomment-629770917

**Comment by xyr5668** [comment]
Thx 回去就试试
2020年6月12日 +0800 PM3:22 lkmvip <notifications@github.com>，写道：
