### ISSUE TITLE
Doesn't work with Netflix's new CDN

### ISSUE THREAD

**Issue by redHat-arko** [lkmvip/netflix-4K-DDplus#32]
It seems that Netflix recently changed its CDN and this extension now doesn't work with it. The same issue was found in Chrome  but ver. 1.24.1 of jangxx/netflix-1080p (https://github.com/jangxx/netflix-1080p) fixed it. Please try and fix the issue in Edge. The issue can be verified by opening the video info tab on Netflix which plays a maximum 720p with avchigh and 1080p with avc (when Playready is enabled), along with HE-AAC 2.0 audio only.

**Comment by markey** [comment]
Can confirm, but this seemed to fix it for me, for now:


![image](https://user-images.githubusercontent.com/470918/119063177-c38ffc80-b9d8-11eb-92ed-05f034f5e68a.png)

**Comment by redHat-arko** [comment]
You mean you get the 640 kb/s DD+ track with this? I mean, I can still watch 1080p video with Playready enabled but my audio is limited to 128 kb/s HE-AAC 2.0.

Enabling the 'disguised as Edge' option did not seem to do anything for me.
