### ISSUE TITLE
note,win10 users, please upgrade your Windows to a version greater than 20H1

### ISSUE THREAD

**Issue by lkmvip** [lkmvip/netflix-4K-DDplus#33]
In this version, 4K can be played perfectly. At the same time, Netflix provides "AVC code" by default, so for these reasons, I have removed the "Disguised as Edge" option and will change the "Force Avc Code" option to "Force Avc High"  in the future

**Comment by drujd** [comment]
I am running

Edition	Windows 10 Pro
Version	21H1
Installed on	‎2021-‎05-‎24
OS build	19043.1081

and I still get AVC High by default (with or without your extension). Therefore, there is no way for me to select the AVC Main codec. The only way for me to play AVC Main is the Windows App (that does not support any other audio than LC-AAC). Could you please re-add support for forcing AVC Main?

**Comment by phanluchoaofficial20** [comment]
Hello,

I'm still cannot watch 4K video on my computer, I have already use ULTRA HD pack but they still not work, I use win 11 pro, microsoft edge to play but......................... not work!

Can you fix help me, I just see 1080p is max!

Thanks

**Comment by lkmvip** [comment]
https://help.netflix.com/zh-tw/node/23931

**Comment by phanluchoaofficial20** [comment]
> https://help.netflix.com/zh-tw/node/23931

I meet all the requirement but they still cannot see 4K title or 4k quality

**Comment by lkmvip** [comment]
contact Netflix service staff

**Comment by Sparoney** [comment]
> I am running
> 
> Edition Windows 10 Pro
> Version 21H1
> Installed on ‎2021-‎05-‎24
> OS build 19043.1081
> 
> and I still get AVC High by default (with or without your extension). Therefore, there is no way for me to select the AVC Main codec. The only way for me to play AVC Main is the Windows App (that, at least without HDCP support, does not allow me to select any other audio codec other than LC-AAC). Maybe this depends on the CDN? Could you please re-add support for forcing AVC Main, if it is even possible?

I have the same issue as you, I forked it and fixed it for myself if you want to try that

**Comment by serialpotato** [comment]
> > I am running
> > Edition Windows 10 Pro
> > Version 21H1
> > Installed on ‎2021-‎05-‎24
> > OS build 19043.1081
> > and I still get AVC High by default (with or without your extension). Therefore, there is no way for me to select the AVC Main codec. The only way for me to play AVC Main is the Windows App (that, at least without HDCP support, does not allow me to select any other audio codec other than LC-AAC). Maybe this depends on the CDN? Could you please re-add support for forcing AVC Main, if it is even possible?
> 
> I have the same issue as you, I forked it and fixed it for myself if you want to try that @drujd

Can I try it?

**Comment by Sparoney** [comment]
> Can I try it?

Yes of course! Here you go: https://github.com/Sparoney/netflix-4K-DDplus

**Comment by Monstermaddy45** [comment]
Not showing Dolby digital Plus and Dolby Atmos

**Comment by drujd** [comment]
@Sparoney It works perfectly (even Atmos/DD+ works for me)! Some titles are better with standard AVC, some are better with AVC high, so having the ability to switch easily is great.

I just wish this was available in the official extension in Edge store, so I wouldn't get the 'developer extension' warnings and got automatic updates, but oh well... Some titles are better with standard AVC, some are better with AVC high, so having the ability to switch is great. I really don't understand why @lkmvip refuses to acknowledge that, but oh well, your fork is better and I will keep using it.

**Comment by lkmvip** [comment]
Choose what you like, use what you like.

I will only make appropriate changes to Netflix’s latest move, and will not make changes due to your individual differences
