### ISSUE TITLE
allow screencapture?

### ISSUE THREAD

**Issue by AARP41298** [lkmvip/netflix-4K-DDplus#34]
I now that this is not the objective of this plugin but let me explain

I want to use prismatik (ambilight diy) and it need screen capure that i could solve running edge in sandboxie

The audio quality keeps, but the video breaks, i think that edge do a validation if the browser is inside of a sandbox, its the only idea i have

> edge with netflix 4k ddplus
![image](https://user-images.githubusercontent.com/33246631/121096254-73c27b00-c7b7-11eb-89f6-6def78111347.png)

> Sandboxied Edge with netflix 4k ddplus
![image](https://user-images.githubusercontent.com/33246631/121095879-c3547700-c7b6-11eb-829f-fe4166907bf2.png)

Firefox natively support screen capture because:
> Firefox for desktop supports the Google Widevine CDM for playing DRM-controlled content. Firefox downloads and enables the Google Widevine CDM by default to give users a smooth experience on sites that require DRM. The CDM runs in a separate container called a sandbox and you will be notified when a CDM is in use.
You can also disable a CDM and opt out of future updates by following the steps below. Once you disable a CDM, however, sites using this type of DRM may not operate properly.

**Comment by lkmvip** [comment]
can't
