### ISSUE TITLE
现在用不了了？

### ISSUE THREAD

**Issue by majiajin2043** [lkmvip/netflix-4K-DDplus#38]

**Comment by majiajin2043** [comment]
2021年6月28日 16:24:45
21H1版本
扩展选项消失了，以前右键扩展图标是有扩展选项的
目前不开扩展可以使用AVC编码（码率较高的），但没有5.1声道和多国字幕了
开启扩展则是highavc编码，码率偏低，有5.1声道和多国字幕了

**Comment by lkmvip** [comment]
点扩展的图标有选项

**Comment by majiajin2043** [comment]
> 点扩展的图标有选项

呜呜呜，终于找到了，sorry，我错怪你了。这个扩展太好用了！

**Comment by majiajin2043** [comment]
AVC编码也找到了，感谢！
