### ISSUE TITLE
裝了開啓設定之後 一直轉圈圈？

### ISSUE THREAD

**Issue by s3327445** [lkmvip/netflix-4K-DDplus#39]
如題 

還有L大能釋出FOR CHROME安裝的版本嗎？ 你的設定裏面有FOR 其他瀏覽器的 可是目前只有EDGE能裝 
 
謝謝

**Comment by s3327445** [comment]
剛剛測可以成功觸發ATMOS了，不過4K還是不能播，一定要買4K熒幕才能對嗎？

**Comment by lkmvip** [comment]
> 剛剛測可以成功觸發ATMOS了，不過4K還是不能播，一定要買4K熒幕才能對嗎？

yes

**Comment by s3327445** [comment]
THX
