### ISSUE TITLE
1080p video problem !?

### ISSUE THREAD

**Issue by tmac21** [lkmvip/netflix-4K-DDplus#40]
Hello sir, I am using Edge for this app but I can't watch 1080p, just I can watching 720p, please fix it. I am using win 8.1

**Comment by lkmvip** [comment]
![22222](https://user-images.githubusercontent.com/12974141/125241655-4de04700-e31e-11eb-8615-0faa8960b5c7.png)

**Comment by tmac21** [comment]
You can't do that for win 8.1 ?

**Comment by lkmvip** [comment]
![asddd](https://user-images.githubusercontent.com/12974141/125567391-b812ef45-ade5-41d5-a351-224b42b44bf8.png)

**Comment by phanluchoaofficial20** [comment]
@lkmvip I cannot click to extension to choose quality on video NF, I use Microsoft Edge!
