### ISSUE TITLE
AVC not working (only avchigh) on extension update

### ISSUE THREAD

**Issue by Sparoney** [lkmvip/netflix-4K-DDplus#41]
Hi,

It appears as though **avc** doesn't work anymore, only **avchigh**. Ticking and unticking the "Use AVC-High insted of AVC video code" option doesn't do anything.

Was just wondering if there is any possibility of this being fixed again? The Windows 10 app still uses **avc**.

**Edge:** ``Video Track: Codec: video/mp4;codecs=avc1.640028 (avchigh)`` (bitrate 2431)
**Windows 10 App:** ``Video Track: Codec: video/mp4;codecs=avc1.640028 (avc)`` (bitrate 4420)

Thanks!

**Comment by theincognito-inc** [comment]
Weird. AVC still works for me on latest Edge Stable and even on Edge Dev (Version 93.0.946.1).
I am on a non 4K plan (Max 1080p resolution) with a normal 1080p monitor.

**Comment by Sparoney** [comment]
> Weird. AVC still works for me on latest Edge Stable and even on Edge Dev (Version 93.0.946.1).
> I am on a non 4K plan (Max 1080p resolution) with a normal 1080p monitor.
> 
> Checked on Chrome too. It uses VP9 by default and using the extension gives me AVCHigh.

Using latest Edge Stable, AVC High is the only one that works for me, normal AVC doesn't. 

I'm also using 1080p plan on a 1080p monitor.

Weird that it works for you but not me

**Comment by Sparoney** [comment]
Sidenote: in older versions of the extension the "Use AVC-High instead of AVC video code" option was different, it was actually "Use AVC not AVC High". AVC High was the default, and normal AVC had to be turned on with the extension. Now it seems it's the opposite, but leaving it off doesn't change anything and still plays AVC High

**Comment by Sparoney** [comment]
Some further testing:

Changing the User Agent of the browser to what the Windows 10 App uses (``Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19043``) causes Netflix to say "Pardon the interruption" when attempting to watch anything.

**Comment by theincognito-inc** [comment]
You are on chromium edge right? Also, checkout edge dev/beta too. Maybe something broke on stable?

**Comment by Sparoney** [comment]
Just tried the Edge Canary, still only AVC High. Also tried Chrome with the original Netflix 1080p extension which has been updated, and that also was AVC High. Are you sure normal AVC is working for you and it's not just AVC High?

Thanks for your help though, guess I'll just use the clunky Windows app for now :)

**Comment by Sparoney** [comment]
UPDATE: Just tried the latest GitHub Release (v1.41), and forcing AVC works!! Seems like there's been a change to the extension and/or server-side between the updates

**Comment by Sparoney** [comment]
Fixed in https://github.com/lkmvip/netflix-4K-DDplus/pull/42

**Comment by lkmvip** [comment]
install new windows10 an full install edge, dont use protableEdge

**Comment by Sparoney** [comment]
I have WIndows 21H1, and I have the full Edge, even tried using Edge Canary. Is there something else going on do you think maybe??

**Comment by lkmvip** [comment]
Netflix already provides avc for edge by default. If you can’t use it, you should find the reason on your own, for example, try to reinstall Windows 10.

**Comment by drujd** [comment]
@lkmvip You are wrong, there are many people running 21H1 and getting avchigh (with or without the extension), not avc (main). Maybe it's datacenter specific, maybe something else, but avc (main) is NOT the default (for many of us, at least). So the option to force it would still be very useful.

**Comment by Sparoney** [comment]
@drujd I forked the repo and put the feature back in for myself, feel free to use it [here](https://github.com/Sparoney/netflix-4K-DDplus)
