### ISSUE TITLE
在进行操作后出现服务中断的问题（Error code: D7375）

### ISSUE THREAD

**Issue by chanssl** [lkmvip/netflix-4K-DDplus#43]
系统版本：Windows 10 19043.1110 (21H1)
浏览器版本：Edge 92.0.902.55（64位）
扩展版本：1.51

操作：拉动视频进度条、点击快进10s/后退10s按钮、暂停视频后播放、选择音轨或字幕。
在以上操作后，会出现视频服务中断的问题，错误码为D7375。

![插件设置](https://user-images.githubusercontent.com/4261299/127333389-ee9d03a5-9024-4faf-aa0b-7d434e2d342d.jpg)

![视频服务中断](https://user-images.githubusercontent.com/4261299/127333119-2703ff06-bc93-4fb4-92d6-f1782e760b11.jpg)

**Comment by lkmvip** [comment]
本地实测无法复现，你可以尝试联系Netflix客服汇报这个D7375问题，他们会在线帮你调试

7375根据知识库来说是扩展引起的问题，你也可以尝试禁用所有扩展后看看是否正常，再一点点开启测试

https://help.netflix.com/zh-tw/node/66764
https://help.netflix.com/zh-TW/node/66763

**Comment by chanssl** [comment]
@lkmvip 确认是由于我本地一个脚本导致，感谢。打扰了。
