### ISSUE TITLE
No 1080p playback, from Chrome.

### ISSUE THREAD

**Issue by balleno75** [lkmvip/netflix-4K-DDplus#46]
Hello, since a few days, certain movies on Netflix, do not play at 1080p, from Chrome.

In Chrome, movie "The Midnight Meat Train (2008)"

![image](https://user-images.githubusercontent.com/39314271/129782998-743adb81-771a-4640-ae79-fab673b3a501.png)

![image](https://user-images.githubusercontent.com/39314271/129783468-5d6e599d-a65b-4ae1-adad-301d40c4f479.png)

![image](https://user-images.githubusercontent.com/39314271/129783879-1c210be7-86ef-49b7-b84d-c36d7cb66d08.png)

In Edge,

![image](https://user-images.githubusercontent.com/39314271/129784117-f2315fe9-a7da-446d-b4a7-d83543b40b66.png)

![image](https://user-images.githubusercontent.com/39314271/129784193-fe8396d7-4d56-4b0d-9b34-92bca79f5f0f.png)

![image](https://user-images.githubusercontent.com/39314271/129784329-09ff663b-0187-41a2-b772-2624f7ddf365.png)

Please can you review it? Also, is it possible to play movies in HEVC format, instead of AVC on Netflix and from Chrome?

Thanks a lot. A greeting.

**Comment by lkmvip** [comment]
Chrome  uses WidevineCdm , Many copyright providers do not recognize it, so in this DRM, only the lowest bit rate can be used

So I said in the README
> 1, Max 1080P

**Comment by balleno75** [comment]
Hi @lkmvip, I think I have explained myself wrong. The movie that I indicate in this post, has a maximum resolution of 1080p on Netflix and through Chrome, with the 1080P option active, it does not reach a 720p resolution, as I indicate in the screenshots. This is independent of whether the movie or series has a 4k resolution, since it can only be viewed in Edge.

Please, check what I tell you since there are several movies and series with this problem and that their display does not reach 720p.

Thank you! very much.

**Comment by lkmvip** [comment]
Chrome uses WidevineCdm , Many copyright providers do not recognize it, so in this DRM, only the lowest bit rate can be used

So I said in the README


win10+full install edge was use PlayReadDrm, its "safe" so，max 4K


WidevineCdm = non safe = 360P～1080P

PlayReadDrm = safe = 360P～4K


As for why Netflix is ​​set in this way, please contact Netflix customer service
