### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cezaloko** [lkmvip/netflix-4K-DDplus#50]
i having a error  D7361-1253 when i change to avc high

**Comment by lkmvip** [comment]
Edge needs > v89.0.715.0

**Comment by cezaloko** [comment]
but i have the latest version of edge,does it work just with that version?

**Comment by lkmvip** [comment]
Give me movieid

**Comment by cezaloko** [comment]
what is that?

**Comment by lkmvip** [comment]
ctrl+shift+alt+d

see MovieId

**Comment by cezaloko** [comment]
80187198

**Comment by lkmvip** [comment]
Netflix seems to no longer configure avchigh for the high-security edge, if you really need it, you can solve it by turning off playreadydrm
Enter the following in the edge address bar and select disabled

edge://flags/#edge-playready-drm-win10

**Comment by lkmvip** [comment]
Enter the following in the edge address bar and select enabled, then restart edge

edge://flags/#edge-playready-drm-win10

I tested it and it works

**Comment by cezaloko** [comment]
when i disabled it works, when i enable again it doesn´t.but when i leave disabled the avc do not work.

**Comment by lkmvip** [comment]
select enabled

**Comment by ofgowtham** [comment]
It's not working for me as well. It shows D5376, but my Edge is updated with 94.0.992.38. Also I left edge://flags/#edge-playready-drm-win10 enabled like mentioned above, no luck. This is the movieId 81240606. All the extension options have been turned on including AVC. Any solution?

**Comment by lkmvip** [comment]
try edge v93

**Comment by ofgowtham** [comment]
> try edge v93

Thanks for the fast reply. It worked like a charm. So should I not update ever from v93?

**Comment by lkmvip** [comment]
I use v93

v94, I found some problems, so I didn’t use it

**Comment by cezaloko** [comment]
how do I  change to a previous version of the edge? thanks for the info by
the way

Em ter., 5 de out. de 2021 às 01:47, lkmvip ***@***.***>
escreveu:

**Comment by ofgowtham** [comment]
> > > Tonight noticed that Edge 94.0.992.38 doesn't go above 1080p. (yesterday was working just fine) But Microsoft Edge Beta version 95.0.1020.14 there is 4k playback on the same videos
> > > So its another option instead of rollback to 93 version is to use beta channel right now until issues with Netflix on the official build is resolved
> > > exactly same video on edge 94 and 95 you see the difference in max bitrate :
> > > ![08102](https://user-images.githubusercontent.com/68902338/136465814-98db93a3-1355-41cd-8c26-92f495c6c65a.png) ![0810](https://user-images.githubusercontent.com/68902338/136466063-2d231326-00a6-4ab5-963e-7465152fc62b.png)
> > 
> > 
> > It was working fine till yesterday. Today its throwing D7361-1253. I can't seem to find any fix.
> 
> To me Edge (main) version 94.0.992.47 works exellent. As for the error i sometime recieve this. You should clear cookies and cache on Netflix then restart Edge or easier download this extension Clear Website Session - https://chrome.google.com/webstore/detail/clear-website-session/cklopogiapaonibagnhmannenniecpfo and while on Netflix.com right click mouse and chose in Clear Website Session - Clear all+ reload page and then restart browser also.

Did everything. Still no luck brother :(

**Comment by Phoenomenal** [comment]
> > > > Tonight noticed that Edge 94.0.992.38 doesn't go above 1080p. (yesterday was working just fine) But Microsoft Edge Beta version 95.0.1020.14 there is 4k playback on the same videos
> > > > So its another option instead of rollback to 93 version is to use beta channel right now until issues with Netflix on the official build is resolved
> > > > exactly same video on edge 94 and 95 you see the difference in max bitrate :
> > > > ![08102](https://user-images.githubusercontent.com/68902338/136465814-98db93a3-1355-41cd-8c26-92f495c6c65a.png) ![0810](https://user-images.githubusercontent.com/68902338/136466063-2d231326-00a6-4ab5-963e-7465152fc62b.png)
> > > 
> > > 
> > > It was working fine till yesterday. Today its throwing D7361-1253. I can't seem to find any fix.
> > 
> > 
> > To me Edge (main) version 94.0.992.47 works exellent. As for the error i sometime recieve this. You should clear cookies and cache on Netflix then restart Edge or easier download this extension Clear Website Session - https://chrome.google.com/webstore/detail/clear-website-session/cklopogiapaonibagnhmannenniecpfo and while on Netflix.com right click mouse and chose in Clear Website Session - Clear all+ reload page and then restart browser also.
> 
> Did everything. Still no luck brother :(

Try different Microsoft Edge channel (Beta or Dev) and see how its going,
Also type in url field -  edge://flags   and enable there    PlayReady DRM for Windows 10 setting  but disable  Hardware-accelerated video decode and Hardware-accelerated video encode (like in picture below)  These settings works best for me, before disable  Hardware-accelerated video encode and decode i was having many trouble while watching Netflix including buffering, some strange lines on video appear  sometimes  even BSOD .   It was crazy, once i turn it off 2 month ago i have no problem, only sometimes error codes like you have.  But after clear cache/cookie and restart edge all works great again ....  well until another code error happens

 
![Screenshot_1](https://user-images.githubusercontent.com/68902338/137164265-0f8be771-6790-4dff-a6ff-a78a286de601.png)

**Comment by Phoenomenal** [comment]
Well it seems no 4k playback to me again, everuthin was fine about 6 hours ago.    This time i locked on 1080p on both Edge v 94 and 95.  Windows 10 app also no 4k playback (max is 1080 + hdr works)   Anyone with the same problem here ?
There definitely  something goes on with Netflix and pc  right now as many people having all kind of problems.....

**Comment by lkmvip** [comment]
stable 94.0.992.50 has been fixed

**Comment by lkmvip** [comment]
![1](https://user-images.githubusercontent.com/12974141/137892624-fbcc8c35-d161-4773-999e-77d1b0fc8754.png)
![2](https://user-images.githubusercontent.com/12974141/137892615-afbe12a1-f71c-4172-81aa-0573fec88238.png)
![3](https://user-images.githubusercontent.com/12974141/137892630-f4271fd2-530b-4d74-924f-b3bef1e95895.png)

**Comment by Dark4Codrutz** [comment]
If anyone needs the free HEVC Video Extension you can install the OEM variant of it using https://store.rg-adguard.net , just search for **9n4wgh0z6vhq** ProductID.
It used to be available from the store page directly but now it asks to Redeem a code instead. With that website you can bypass and download the appx directly. Future versions will autoupdate from Windows Store as expected.

TBH I still don't know if Edge Chromium makes use of this UWP Video Extension. It is supposed to be for UWP apps like Edge Legacy and UWP Video Players (like default Film & TV app)
