### ISSUE TITLE
AVC Main for Windows 11

### ISSUE THREAD

**Issue by phanluchoaofficial20** [lkmvip/netflix-4K-DDplus#51]
1. Your question may be closed by me soon, don’t ask me why, if you have to answer, then the answer is that I have social phobia
2. If you find a problem and you have a solution, then you can choose to submit it together. Of course, your issuse may also be closed by me. don’t ask me why, if you have to answer, then the answer is that I have social phobia
3. If you have a good idea, please pull to me. Of course, your pull or issue may also be closed by me. don’t ask me why, if you have to answer, then the answer is that I have social phobia

**So, the point is, I have social phobia, if not necessary, please do not issue or pull at will, thank you**

Hello,

Now, I have use Windows 11 x64 and I use your extension to force to use AVC instead of AVCHigh in Microsoft Edge in Windows 11, but now I'm in Windows 11 and don't work with this. Can you update using AVCMain for Windows 10 and Windows 11 ?

Thanks!

**Comment by theincognito-inc** [comment]
@phanluchoaofficial20 Hi. I am on Win 11 Pro x64 (build 22000.176) with built in Edge (64bit, v93.0.961.38). AVC and AVC High work fine here, using the extension.

**Comment by fosam** [comment]
@phanluchoaofficial20 Join our [group](https://t.me/joinchat/kHRk0tIH0dNhOGE0) maybe you can find some help there.

**Comment by phanluchoaofficial20** [comment]
Can I know your solution and extension because I force NF to work with AVC
instead AvCHigh but they dont work. I use Edge

Vào Th 6, 10 thg 9, 2021 lúc 19:52 f054m ***@***.***> đã viết:

**Comment by phanluchoaofficial20** [comment]
> @phanluchoaofficial20 Hi. I am on Win 11 Pro x64 (build 22000.176) with built in Edge (64bit, v93.0.961.38). AVC and AVC High work fine here, using the extension.
> And, btw, @lkmvip 's extension forces AVC High, not AVC. Are you sure you are using the right extension?

Can you send me the extension with work for AVC Main for Win 11 ?

**Comment by phanluchoaofficial20** [comment]
> @phanluchoaofficial20 Hi. I am on Win 11 Pro x64 (build 22000.176) with built in Edge (64bit, v93.0.961.38). AVC and AVC High work fine here, using the extension.
> And, btw, @lkmvip 's extension forces AVC High, not AVC. Are you sure you are using the right extension?

And do you  know how to decrypt video AVC Main after download video stream AVCMain of NF ?

**Comment by lkmvip** [comment]
Netflix's promised operating system does not include Windows 11

Please wait for Netflix

We will not discuss how to decrypt Netflix video or audio files here
