### ISSUE TITLE
Bitrate menu not clickable

### ISSUE THREAD

**Issue by Jowat97** [lkmvip/netflix-4K-DDplus#52]
Hello @lkmvip !

Unfortunately, the bitrate menu is not clickable anymore. You can still open it, but if you try to click it, the click won't get registered and instead it will pause/play the video. I don't know if this is fixable but it would be really nice!

Because it seems like the "select best bitrate" is not working anymore, therefore I need to choose it manually.

Best regards!

**Comment by lkmvip** [comment]
https://github.com/lkmvip/netflix-4K-DDplus/archive/refs/heads/master.zip

**Comment by Jowat97** [comment]
You are awesome! Works perfectly. 👍🏾
