### ISSUE TITLE
Extension not updated on the Store

### ISSUE THREAD

**Issue by edge261** [lkmvip/netflix-4K-DDplus#55]
1. Your question may be closed by me soon, don’t ask me why, if you have to answer, then the answer is that I have social phobia
2. If you find a problem and you have a solution, then you can choose to submit it together. Of course, your issuse may also be closed by me. don’t ask me why, if you have to answer, then the answer is that I have social phobia
3. If you have a good idea, please pull to me. Of course, your pull or issue may also be closed by me. don’t ask me why, if you have to answer, then the answer is that I have social phobia

**So, the point is, I have social phobia, if not necessary, please do not issue or pull at will, thank you**
___________________________________

The version of the extension that I get when I install it is the 1.51, without the option to force HEVC. I'm installing it from the wrong source?

**Comment by lkmvip** [comment]
use github version
