### ISSUE TITLE
Any way to use this in Netflix UWP app?

### ISSUE THREAD

**Issue by ANONIMNIQ** [lkmvip/netflix-4K-DDplus#59]
I tried it in Edge and it works perfect, but at some point when I watched Netflix in 4K,when I switched windows HDR on, something happened and driver crashed with error message "Default Radeon WattMan settings has been restored due to unexpected situation". After that, I lose HDCP 2.2. and HEVC 4K in Edge. I tried to reinstall my display drivers, I delete the old one with official amd cleanup utility in safe mode and then install latest drivers, reinstall Edge but nothing helped. Netflix UWP app works ok, but I miss great features of this extension. Any way to use it with Netflix app?

**Comment by lkmvip** [comment]
none
