### ISSUE TITLE
[Feature Request] Force Edge to stream avc instead of avchigh.

### ISSUE THREAD

**Issue by Sparoney** [lkmvip/netflix-4K-DDplus#6]
Hi,

In Microsoft Edge, Netflix streams using a high-efficiency codec (**avchigh**) compared to the Windows 10 app which just uses **avc**. With avchigh, the bitrate is lower (because it's high-efficiency) but the quality looks worse compared to the Windows 10 app which uses avc. You can see on this Reddit post: https://www.reddit.com/r/MicrosoftEdge/comments/hg6aim/netflix_stream_bitrate_problem/

Edge: 1630 bitrate, avchigh (1080p)
Windows 10 app: 4220 bitrate, avc (1080p)

I was wondering if there was a way for you to implement a feature to force Edge to only use avc streams like the Windows 10 app instead of avchigh in order to get a higher bitrate?

Thanks!

**Comment by lkmvip** [comment]
I will add a switch in next release

But are you sure that avc is really better than avchigh?


in this episodes https://www.netflix.com/title/81036944  S2E10


![sdf](https://user-images.githubusercontent.com/12974141/88677859-61e86400-d120-11ea-993b-8f47ea92b8cb.png)

**Comment by Sparoney** [comment]
> 
> But are you sure that avc is really better than avchigh?
> 

I get that with the higher efficiency they can lower the bitrate and file size by a lot but personally, I compared a couple shows avc vs avchigh (Outer Banks, 13 Reasons Why, and Bojack Horseman) and the higher bitrate avc just looked much better.

**Comment by lkmvip** [comment]
I didn't see any obvious difference....If you can elaborate

I did not bypass DRM, you can see that all files are encrypted.

**Comment by Sparoney** [comment]
Sorry, my bad thinking you bypassed the DRM, I didn’t see the “encryption” at the bottom.

In terms of the difference I noticed, (using your example):
AVC: 6129 bitrate, 2GB file
AVC High: 2505 bitrate, 867MB file
Since it’s high efficiency this is why the bitrate is lower and it’s “supposed” to look the same as the 6mbps AVC.
However I’ve noticed (at least on shows i’ve watched) that the higher bitrate avc looks better. I guess overall it comes down to each show and episode because of its encoding but personally I just prefer normal avc as it’s not high-efficiency and has a higher bitrate.

It’s basically H.265 vs H.264. Some people prefer H.265 because of the smaller file size and others prefer H.264 because it’s usually better quality.

Sorry if i’ve confused you at all and hope this clears it up. If it’s too difficult/not possible to implement then that’s ok!

**Comment by lkmvip** [comment]
ok, now  I have implemented this feature and tested it without any problems. I will upload the update later today

**Comment by Sparoney** [comment]
> ok, now I have implemented this feature and tested it without any problems. I will upload the update later today

Thank you so much! You're amazing. Stay safe.

**Comment by Sparoney** [comment]
Tested and works. Thank you so much!

**Comment by Liqianyu** [comment]
According to testing this feature is currently not working, has the Netflix server changed or something? Can anyone confirm the VMAF for AVC Vs AVC High now?

**Comment by erickyun** [comment]
> This feature is currently not working.
> The Netflix UWP App still uses AVC.
> https://netflixtechblog.com/4b9464204830
> I think AVC = AVC Main\AVC High = AVCHi-Opt.
> Is there any evidence now that AVC encodes higher image quality than AVCHigh?

Did you find any fix for this? I have the same problem now?

**Comment by Sparoney** [comment]
Hey @erickyun @Liqianyu 

I don't have Netflix anymore but when I used it these are the examples I remember on testing it:
Bojack Horseman, AVC High bitrate was around 900, looked awful, AVC normal was like 2000+ and looked clearer
13 Reasons Why, AVC High bitrate was around 2000 and looked grainy, AVC normal was at least 4000 and looked much better

I could definitely see the difference, hopefully this can be fixed again

**Comment by pikopikopikopiko** [comment]
yeap seems netflix and widevine blocks avc main profile, You can watch with playready enabled avc main,
on widevine there is an error that does not allow to play that profile, and need to cheat app that its somehow the netflix app not an browser I think
