### ISSUE TITLE
Dolby audio

### ISSUE THREAD

**Issue by darekpro** [lkmvip/netflix-4K-DDplus#60]
Hello, long time ago I use plugin with Win10/Edge and everything working perfect, but now I see only AAC track 2.0 and 5.1 if I select HE-AAC. There is any actual problem with forced enable dolby track?

**Comment by lkmvip** [comment]
HE-AAC work on  chrome

ddplus work on full installed EDGE，and need win10

**Comment by darekpro** [comment]
Yep I know, I use Edge and win10, any not working for me now.

**Comment by darekpro** [comment]
![Zrzut ekranu z 2022-05-22 10-38-40](https://user-images.githubusercontent.com/58607093/169686207-cf059ae9-54cd-4539-a5b0-a45f3499d227.png)
![Zrzut ekranu z 2022-05-22 10-38-48](https://user-images.githubusercontent.com/58607093/169686209-3470d802-30ed-40a6-8d98-c6c26d969408.png)

**Comment by darekpro** [comment]
Like i say dolby working for my few months ago but not for now.

**Comment by lkmvip** [comment]
try this version
https://github.com/lkmvip/netflix-4K-DDplus/archive/refs/heads/master.zip

**Comment by darekpro** [comment]
Hmm
![Zrzut ekranu z 2022-05-22 11-17-44](https://user-images.githubusercontent.com/58607093/169688303-022131ca-c51d-4544-9fb5-be73429f0e60.png)
![Zrzut ekranu z 2022-05-22 11-17-49](https://user-images.githubusercontent.com/58607093/169688304-6bda4d16-843d-46ef-aa7b-0d2288627597.png)

**Comment by darekpro** [comment]
I ok checked on another notebook and showing DDplus, so something is wrong with my virtual machine with Win10.
Sorry for the false problem.

**Comment by Guenito** [comment]
Hello,
Do you know why from one episode to another Netflix goes from 5.1 to 2.0 during the same season?
I tried on Edge with the extension and even on the application it is. Do you have any idea of this inconsistency?
Thanks.
