### ISSUE TITLE
Force AVC video codec playback instead of AVC-High for maximum bitrate

### ISSUE THREAD

**Issue by Dijitul1029** [lkmvip/netflix-4K-DDplus#61]
Are you able to make a cadmium playercore js file that force enables only certain options? I'd like to force enable The options I want force enabled are "Focus 1080p", "Play with AVC" under Video Configuration, and "Show all audio tracks and subs" and "Automatically select best bitrate available". My purpose of requesting this is that I don't want my browser/program to play any other video codecs besides AVC, specifically I don't want to get the "avchigh" stream, but I can't install the extension source code as normal so I think my only choice is to request that all code associated with "Play AV1" "Play with VP9" "Play with "AVC-High" and "Play with Netflix's default settings" be removed from a version of the cadmium playercore for those of us to want only the highest bitrate possible with "Play with AVC" being the only stream requested by the browser (at least from within a browser such as chrome or edge) Basically is there a way to edit the cadmium playercore js file to only have "Play with AVC" selected as the video codec being requested.

**Comment by lkmvip** [comment]
i cant help you
