### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by grumpycalabi314** [lkmvip/netflix-4K-DDplus#64]
Hi! Unfortunately the extension isn't working on Linux. Netflix simply refuses to play.

Edit: I'm on Fedora 37, with Gnome 43.2 and the latest stable build of Edge.

**Comment by lonkarjay** [comment]
Unfortunately, it is also not working on Windows 10, anymore.
I guess it has something to do with latest update of Microsoft Edge itself.
Hopefully someone notices this so that it gets fixed.

**Comment by lonkarjay** [comment]
I think there have been some major changes in the Cadmium PlayerCore library by Netflix itself, because, I tested with other plugins also, none of them are now working on any of the browsers!

**Comment by lonkarjay** [comment]
Hello, can you see if your Netflix Video Quality was set to low? Mine was, I set it to High, reloaded the plugin and everything is now fine.

**Comment by grumpycalabi314** [comment]
Nope, neither on Auto or High. I'm getting D7121-1331

**Comment by lonkarjay** [comment]
Oh, no. Guess I got lucky, I am on Windows 10, though.
