### ISSUE TITLE
Netflix最近上线的新剧集字幕会变得特别小，且无法调整字幕的大小

### ISSUE THREAD

**Issue by panggino** [lkmvip/netflix-4K-DDplus#70]
如题，好像是因为插件会把中文字幕强制设定成旧样式的关系，使用edge观看时，中文字幕会变得特别小，且无法透过帐户的偏好设定调整。切换成其他浏览器观看后，便能显示正常大小的新版字幕。希望您可以帮忙解决此问题，谢谢。

**Comment by lkmvip** [comment]
网飞的原因，老版是图片字幕，新的字幕会变小，以后不知道会不会变回来，因为王冠第六季有些集数是正常的，只有第二集不正常，考虑到网飞已经强推新字幕格式的情况，所以昨天更新了版本对新版字幕样式进行适当优化（需重置网飞账号内的字幕个性化设置）

后续我也会增加选项给老版的字幕，目前能实现普通放大（比老版的略微小点，但是清晰），略损放大（比老版的略大，但是略微模糊）

![f1](https://github.com/lkmvip/netflix-4K-DDplus/assets/12974141/9d862605-0d7d-44cc-a5fb-6aecd6114274)
![f2](https://github.com/lkmvip/netflix-4K-DDplus/assets/12974141/945e7c8c-f219-46ac-9207-33f5bad4a956)

**Comment by lkmvip** [comment]
网页上看上面的图1可能也有点糊，但是实际上在观影的时候是清晰的。

差不多就这么个意思了，会跟随下一次core更新一起发


![`~UL_H Z}SP$W9) $QQC945](https://github.com/lkmvip/netflix-4K-DDplus/assets/12974141/57e9dc7d-190e-4e30-827d-46c889184042)
