### ISSUE TITLE
Bitrate menu not visible

### ISSUE THREAD

**Issue by Jowat97** [lkmvip/netflix-4K-DDplus#71]
Hey there,

I noticed that in the latest version (downloaded your Git Repo) the Bitrate menu won't show if I press (CTRL + Shift + Alt + S). Nothing happens at all. Tried multiple times. With older versions of this extension it works fine. Maybe one of the last commits broke something.

**EDIT:** I am sorry, I found the mistake. In your latest commit: https://github.com/lkmvip/netflix-4K-DDplus/commit/493d128dc0f766119c112fc808fdcea2fe6b8220, you changed it from 'S' to 'B'. So, it is now: 'CTRL + Shift + Alt + B'. I guess you did it, because 'S' is already used by Netflix for skipping the intro. Great idea! I changed it for myself to A (65), since it feels way more convenient and is similar to the old combination. Also A is not used by Netflix.

You may want to add this to the description? Maybe more people will soon follow and ask why it is not working. :D Also I noticed that the Edge Store version is pretty outdated. It's not important for me, I use always your latest GitHub repo. But maybe for the people using the Edge Store Extension version it would be nice to have the latest update. Thanks for your work, you can close this issue. :)

Cheers!

**Comment by Antivan28** [comment]
Thank you for the info.   I also noticed that CTRL + Shift + Alt + S no longer works, now know the reason and new  combination.

**Comment by lkmvip** [comment]
Turning S into B was a decision made by Netflix.

The ME EDGE store keeps rejecting my new versions, so the store should not be updated
