### ISSUE TITLE
D7355-1204 error when playback

### ISSUE THREAD

**Issue by cytb8** [lkmvip/netflix-4K-DDplus#73]
I started using the MS store version few days ago, it works flawlessly, untill it does not work from yesterday and showed me D7355.  I then installed the pack from Github and it does not work and show me D7355-1204

Any fix to make it work again?

Thanks

**Comment by lkmvip** [comment]
try update your browser

contact Netflix support

**Comment by cytb8** [comment]
Edge is already the latest version 120.0.2210.61

**Comment by Acrivec** [comment]
I have the same issue now and I'm forced to use netflix store app.

**Comment by lkmvip** [comment]
contact the Microsoft EDGE development team. This error has nothing to do with me or Netflix. I have discussed it with Netflix.

**Comment by lkmvip** [comment]
https://github.com/lkmvip/netflix-4K-DDplus/issues/74#issue-2054633803
