### ISSUE TITLE
Getting Error "Title is not available to watch instantly." errorcode : D7111-1331

### ISSUE THREAD

**Issue by itisusamashahid** [lkmvip/netflix-4K-DDplus#75]
OS: Arch
Browser: MS-Edge

I try installing and loading any title on Netflix, but it gives the error "Title is not available to watch instantly." When I uninstall the extension, all titles start to work but with poor quality. :(

![Screenshot_20240224_154313](https://github.com/lkmvip/netflix-4K-DDplus/assets/106423911/bf2bbf0d-b981-4d06-99f2-f59f57007cb3)

**Comment by lkmvip** [comment]
https://help.netflix.com/zh-tw/node/30081
