### ISSUE TITLE
edge can not load this 

### ISSUE THREAD

**Issue by blankhang** [lkmvip/netflix-4K-DDplus#8]
![image](https://user-images.githubusercontent.com/3981276/91971877-7ab1ee00-ed4c-11ea-9dd3-6a7b2af40d1f.png)

**Comment by lkmvip** [comment]
manifest.json  line 8 rename "default_icon" to "128"

**Comment by lucassilvas1** [comment]
I'm still unable to load the extension even after that @lkmvip , when I do what you suggested I get this error instead:
![image](https://user-images.githubusercontent.com/52336985/95464105-f3a9f400-094f-11eb-9548-b243b2fc1bf4.png)

Could you please help me?

**Comment by lkmvip** [comment]
try this

https://microsoftedge.microsoft.com/addons/detail/oikpkeeoofpiapmjioabikmgjeaoggcn
