### ISSUE TITLE
还是不行装不了

### ISSUE THREAD

**Issue by mmeiwenlong** [lkmvip/netflix-4K-DDplus#9]
![QQ截图20201001165843](https://user-images.githubusercontent.com/44661424/94790368-bfdb4580-0408-11eb-90f1-3da304596a34.png)
![QQ截图20201001170641](https://user-images.githubusercontent.com/44661424/94790381-c5d12680-0408-11eb-8582-dfe5dbe4fd07.png)
![QQ截图20201001170347](https://user-images.githubusercontent.com/44661424/94790384-c8338080-0408-11eb-8ed9-dcff108831aa.png)

**Comment by lkmvip** [comment]
那就不清楚了

**Comment by nameless3721** [comment]
下载Source code zip就可以装

**Comment by lkmvip** [comment]
try this

https://microsoftedge.microsoft.com/addons/detail/oikpkeeoofpiapmjioabikmgjeaoggcn
